### ISSUE TITLE
需要帮助

### ISSUE THREAD

**Issue by zhaohyuan123** [tztsai/BS-Sleeping-RL#12]
感谢您上传的代码，这对我帮助非常大。我在运行的时候可以成功执行train.sh,但运行simulate.sh遇到了困难，想问下您用的python、torch以及Stable-Baselines3的版本是什么？如您可以回答，我非常感激。
![1](https://github.com/tztsai/BS-Sleeping-RL/assets/171479901/cf61e6e0-970b-49f5-91aa-cc340183492f)

![2](https://github.com/tztsai/BS-Sleeping-RL/assets/171479901/cd999295-17cc-4d24-816d-f8fdf0a00c49)

**Comment by casterkay** [comment]
你好，第一个错误看起来是没有找到给定配置的模型。请问你是用的wandb还是tensorboard？另外可以在出错的那行代码之前打印搜索的路径看看为什么找不到。第二个错误应该是直接运行simulate.py，没有提供足够CMD参数的原因，跟package的版本没有关系。

**Comment by zhaohyuan123** [comment]
感谢您的回复，我尝试了使用wandb，现在能够成功找到路径；但是关于这个问题，提示训练的模型缺少hidden_size（但是我在训练后的files\config.yml里找到了这些参数），这看起来是训练后的config.yml中的参数并没有传进attr里，我直接输入bash simulate.sh后还需要添加哪些命令语句呢？
![git](https://github.com/tztsai/BS-Sleeping-RL/assets/171479901/86ca07f7-8a9a-4fba-a9a6-008e6095df8b)

**Comment by casterkay** [comment]
不好意思很久没看这个repo了，请问问题还存在吗？
