### ISSUE TITLE
train_dqn.sh运行出现问题

### ISSUE THREAD

**Issue by jianshangmao** [tztsai/BS-Sleeping-RL#15]
作者你好，这是一篇很不错的工作，我科研运行train.sh，但是运行train_dqn.sh运行出现如下问题。
![bce0dc7208b62b1a73125f10b004d9b](https://github.com/user-attachments/assets/4d8c344e-0815-4067-8fd2-6b3e3ceb0276)
请问你有好的建议吗

**Comment by jianshangmao** [comment]
可以运行train.sh

**Comment by casterkay** [comment]
你好，这个应该是gym的版本问题

**Comment by jianshangmao** [comment]
感谢你的帮助，但是我使用和requirements里面gym==0.25.2相同的版本。问题仍未解决。请问你可以告诉我你使用的python，torch，stable-baselines3的相关版本吗？非常感谢。
![image](https://github.com/user-attachments/assets/3937663a-c16b-44d4-ba80-eb7913e01793)

**Comment by casterkay** [comment]
那应该就是stable-baselines3的版本太新了，试试1.5.0可以吗

**Comment by jianshangmao** [comment]
感谢你的回答。我使用stable-baselines3=1.5.0，但是需要将gym降到0.21.0。成功运行train_dqn.sh.但是运行simulate.sh遇到了和#12相同的问题，
![image](https://github.com/user-attachments/assets/75850b0b-a682-4f51-ad3f-a33a173580c4)

**Comment by casterkay** [comment]
你好，simulate.py里的argument parsing的确有些问题，现在已修复

**Comment by casterkay** [comment]
请问问题是否以解决？

**Comment by jianshangmao** [comment]
感谢您的耐心回复！
1、我运行bash train_dqn.sh出现如下报错。
![image](https://github.com/user-attachments/assets/5946a475-b6f4-4e3b-a78d-991b43ecc0b7)
对dqn_trainer.py进行修改
self.observation_space = spaces.Box(low=0.0, high=64.0, shape=(111,), dtype=np.float32)
self.action_space=spaces.Box(low=0.0, high=3.0, shape=(3,), dtype=np.int64)
![image](https://github.com/user-attachments/assets/79f10d34-ac7e-4fa6-8a29-a54871f660e4)
请问这个修改的对吗？
2、运行simulate.sh没有hidden_size报错但是出现了新问题。
![image](https://github.com/user-attachments/assets/2727db76-613d-44ce-b4de-b5c222a61684)

**Comment by casterkay** [comment]
> 感谢您的耐心回复！ 1、我运行bash train_dqn.sh出现如下报错。 ![image](https://private-user-images.githubusercontent.com/80185687/381120471-5946a475-b6f4-4e3b-a78d-991b43ecc0b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzI5NjIsIm5iZiI6MTczMDYzMjY2MiwicGF0aCI6Ii84MDE4NTY4Ny8zODExMjA0NzEtNTk0NmE0NzUtYjZmNC00ZTNiLWE3OGQtOTkxYjQzZWNjMGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDExMTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNmEyNWNlY2E3YWUwNmJlYTZkNzA2NDY4ODJmNDU0NGJlNmU4NmE5YzgzNzQzN2E4MjNhZTJlOTMxOGViZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TqF3ZXP7OP3VNxVqYvIhlTXz3TF9fwd9oEeDyPbgJxg) 对dqn_trainer.py进行修改 self.observation_space = spaces.Box(low=0.0, high=64.0, shape=(111,), dtype=np.float32) self.action_space=spaces.Box(low=0.0, high=3.0, shape=(3,), dtype=np.int64) ![image](https://private-user-images.githubusercontent.com/80185687/381121376-79f10d34-ac7e-4fa6-8a29-a54871f660e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzI5NjIsIm5iZiI6MTczMDYzMjY2MiwicGF0aCI6Ii84MDE4NTY4Ny8zODExMjEzNzYtNzlmMTBkMzQtYWM3ZS00ZmE2LThhMjktYTU0ODcxZjY2MGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDExMTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDhmZDk3MWE4OTA3NWUzNGZiZTk2NGFkZjQ5Y2ExODUwYmU0MzYwMWU2NzIyMzM2ZTUzZmY2MWM4YWM4M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CwJO-PIao2NBzR9gbLuE3pzc1u2U-OEmyrMMnCsdLbI) 请问这个修改的对吗？ 2、运行simulate.sh没有hidden_size报错但是出现了新问题。 ![image](https://private-user-images.githubusercontent.com/80185687/381119395-2727db76-613d-44ce-b4de-b5c222a61684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzI5NjIsIm5iZiI6MTczMDYzMjY2MiwicGF0aCI6Ii84MDE4NTY4Ny8zODExMTkzOTUtMjcyN2RiNzYtNjEzZC00NGNlLWI0ZGUtYjVjMjIyYTYxNjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDExMTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNmJlNzg0ZWVhMzM5ZGU3ZTQxMDBiMWI4NWI1MDMxNGUyMjQ3NDU2OTUxNmFjNmEwNDI2NTZlMDY5M2FlZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9FYgUB1qC7A-h40Kv-zRE2w6jidayk72l1V098ZWDhI)

第一个看起来还是版本问题，这样改应该没事。第二个是不是因为还没有保存训练过的模型啊

**Comment by jianshangmao** [comment]
非常感谢您的回复！
