### ISSUE TITLE
亲爱的师兄，现在这篇文章还没见刊吗？

### ISSUE THREAD

**Issue by atleticozyr** [tztsai/BS-Sleeping-RL#5]
亲爱的师兄，现在这篇文章还没见刊吗？

**Comment by casterkay** [comment]
发到会议上了，不过还没有见刊。但是可以在我学校的网站上找到我这个项目的[硕士论文](http://kth.diva-portal.org/smash/record.jsf?aq2=%5B%5B%5D%5D&c=19&af=%5B%5D&searchType=LIST_LATEST&sortOrder2=title_sort_asc&query=&language=en&pid=diva2%3A1752823&aq=%5B%5B%5D%5D&sf=all&aqe=%5B%5D&sortOrder=author_sort_asc&onlyFullText=false&noOfRows=50&dswid=4010)。

**Comment by atleticozyr** [comment]
谢谢师兄，我拜读一下！感谢！
