### ISSUE TITLE
Where to find the Actual Data

### ISSUE THREAD

**Issue by habte16** [tztsai/BS-Sleeping-RL#6]
Getting deep into your projects, I couldn't find actual data for further study on the subject. Would you provide a link or any means to access the data?

**Comment by casterkay** [comment]
The data is in the `data` folder. And the path to the data file to be used is set at `traffic/config.py`.
![image](https://github.com/tztsai/BS-Sleeping-RL/assets/34415979/2a082678-aed8-4373-bcee-6f34c6955e37)
